clear all
b_vec = [1 : 0.25: 5 ];
%Performance index = System output value when time is around 0.9 seconds.
performanceIndex_vec = [];
for j=1:length(b_vec)
b = b_vec(j); %Here, you chose the value of b.
sim('first_order_system.mdl'); %This automatically simulates your Simulink model. After, the simulation finishes, the time vector called â€œtoutâ€? and output vector called â€œyoutâ€? are automatically generated by the MATLAB/SIMULINK. They are vectors as follows:
[tmpmin index] = min(abs(tout - 6.5)); %Here you find the index in the time-vector which is closest 0.9 seconds.
performanceIndex_vec(j) = yout(index); % Here, you save actual performance in a vector after each simulation.
end
figure, plot(b_vec, performanceIndex_vec, '*-')
xlabel('pole location (-b)'), ylabel('Performance Index'), grid